### ISSUE TITLE
[1.14.4] Incompatable with OptiFine, IllegalAccessError

### ISSUE THREAD

**Issue by Wynadorn** [jaredlll08/Ambient-Environment#5]
Hello Jaredlll08,

I'm getting the following error when trying to run AmbientEnvironment-2.0.0.jar under 1.14.4-forge-28.1.1.jar.

````
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class net.minecraft.world.biome.BiomeColors$IColorResolver from class com.example.examplemod.AmbientEnvironment
	at com.example.examplemod.AmbientEnvironment.doClientStuff(AmbientEnvironment.java:29)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:133)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.world.biome.BiomeColors$IColorResolver from class com.example.examplemod.AmbientEnvironment
````

It is a compatibility issue between OptiFine_1.14.4_HD_U_F4_pre4_MOD.jar and AmbientEnvironment-2.0.0.jar. It might be incompatible with other mods, I've only tested OptiFine and AmbientEnvironment.

AmbientEnvironment works when run on it's own.

Here's the complete log:
https://pastebin.com/raw/rFMdgzP4

**Comment by jaredlll08** [comment]
Nothing I can do, Optifine messes A LOT with minecraft's code.
